#!/usr/bin/env node
/**
 * Fikes Chevrolet Inventory Scraper
 * --------------------------------------------------------------------------
 * Scrapes vehicle data from fikeschevy.com VDPs and generates a Meta
 * (Facebook/Instagram) Commerce Manager automotive XML feed.
 *
 * WHY PUPPETEER:
 * fikeschevy.com runs on Dealer Inspire behind a Cloudflare WAF. Plain HTTP
 * clients (axios, got) — even with full browser headers, cookie jars, and a
 * Referer set — are blocked with a 403. Headless Chrome via Puppeteer, with
 * `--disable-blink-features=AutomationControlled` and a spoofed
 * `navigator.webdriver`, gets past that.
 *
 * WHY THE SITEMAP, NOT THE LISTING PAGES:
 * The /new-vehicles/ and /used-vehicles/ search/listing pages were
 * confirmed to serve a fake "no results" page specifically to Puppeteer's
 * requests — independent of headers, client hints, or cookie/session
 * state. VDP pages themselves were confirmed to load fine throughout; the
 * block was only ever on the listing/search widget. The Yoast SEO XML
 * sitemap at /dealer-inspire-inventory/inventory_sitemap is confirmed to
 * list every current VDP URL directly and unblocked, so this version
 * fetches that sitemap and visits each VDP URL directly — it never touches
 * a listing/search page at all.
 *
 * WHY THE SITEMAP IS FETCHED VIA in-page fetch(), NOT page.goto():
 * The sitemap is a Yoast SEO XML sitemap, which ships with a client-side
 * XSLT stylesheet that Chrome applies when the XML is loaded as a
 * top-level navigation — that's what produces the nice "XML Sitemap /
 * Generated by YoastSEO" human-readable table view a person sees when they
 * open the URL directly in a normal browser tab. Confirmed via direct
 * testing: navigating to this URL with page.goto() and reading
 * response.text() intermittently returns empty/incomplete text — even
 * though the URL is valid, unblocked, and fully populated (68 URLs,
 * confirmed by opening it in a real browser tab) — because Chrome's
 * handling of an XML+XSLT top-level navigation is not equivalent to a
 * plain background HTTP fetch of the same URL. Issuing the request via
 * page.evaluate(() => fetch(url)) from an already-warmed-up page instead
 * treats it as a normal background XHR/fetch, which reliably returns the
 * raw, untransformed XML body — same cookies/session as the navigation
 * would have used, just without Chrome's special document-viewer handling
 * getting in the way.
 *
 * DEDUPE POLICY (read this before touching this file):
 * Every VDP URL discovered is scraped unconditionally. There is NO
 * "skip if already seen" check anywhere inside the scraping loop — that
 * exact pattern previously caused 50 real, unique vehicles to be silently
 * dropped as false-positive duplicates (120 -> 70).
 * The ONLY deduplication in this entire file is one filter pass that runs
 * once, after all scraping has finished, on the completed array. See
 * `main()` near the bottom — search for "THE ONLY DEDUPE PASS".
 *
 * OUTPUT:
 *   docs/inventory.json — raw structured vehicle data
 *   docs/feed.xml        — Meta Commerce Manager Vehicles catalog feed,
 *                          using the <listings><listing> schema (NOT the
 *                          generic <rss><channel><item> Google-base product
 *                          feed format — that schema is silently rejected
 *                          by Commerce Manager for this catalog type with
 *                          "File format isn't supported"). See the comment
 *                          above vehicleToFeedItem() for the full schema
 *                          reference, confirmed against Meta's own
 *                          downloaded XML template and live test uploads.
 * --------------------------------------------------------------------------
 */
'use strict';
const fs = require('fs');
const path = require('path');
const puppeteer = require('puppeteer');
const { XMLValidator } = require('fast-xml-parser');
// ============================================================================
// Config
// ============================================================================
const BASE_URL = 'https://www.fikeschevy.com';
const SITEMAP_URL = `${BASE_URL}/dealer-inspire-inventory/inventory_sitemap`;
const NAV_TIMEOUT_MS = 45000;
const NAV_RETRY_ATTEMPTS = 3;
const REQUEST_DELAY_MS = 1200; // politeness delay between page loads
const PIXEL_ID = '911722818604064';
const DEALER_ADDRESS = {
  street: '771 Military St N',
  city: 'Hamilton',
  state: 'AL',
  zip: '35570',
  country: 'US',
};
const OUTPUT_DIR = path.join(__dirname, 'docs');
const USER_AGENT =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36';
const SEC_CH_UA = '"Chromium";v="125", "Not.A/Brand";v="24", "Google Chrome";v="125"';
const BLOCKED_RESOURCE_TYPES = new Set(['image', 'font', 'media', 'stylesheet']);
// ============================================================================
// VIN / condition extraction from VDP URLs
// ============================================================================
const VIN_FROM_URL_RE = /\/inventory\/[^/]+-([A-HJ-NPR-Z0-9]{17})\/?$/i;
function extractVinFromUrl(rawUrl) {
  const clean = rawUrl.split('?')[0].split('#')[0];
  const match = clean.match(VIN_FROM_URL_RE);
  return match ? match[1].toUpperCase() : null;
}
function isVdpUrl(rawUrl) {
  return /\/inventory\//i.test(rawUrl) && extractVinFromUrl(rawUrl) !== null;
}
const CONDITION_FROM_URL_RE = /\/inventory\/(certified-pre-owned|certified|pre-owned|used|new)-/i;
function extractConditionFromUrl(rawUrl) {
  const match = rawUrl.match(CONDITION_FROM_URL_RE);
  if (!match) return null;
  return match[1].toLowerCase() === 'new' ? 'new' : 'used';
}
// ============================================================================
// Title parsing (year / make / model / trim)
// ============================================================================
const CONDITION_PREFIX_RE = /^(certified\s+pre-?owned|pre-?owned|certified|new|used)\s+/i;
const MODEL_SUFFIX_RE = /^(\d{3,4}(HD)?|EUV|EV|ZR2|ZL1|SS)$/i;
function parseTitle(rawTitle) {
  if (!rawTitle) return { year: null, make: null, model: null, trim: null };
  let title = rawTitle.trim().replace(/\s+/g, ' ');
  title = title.replace(CONDITION_PREFIX_RE, '').trim();
  const parts = title.split(' ').filter(Boolean);
  let idx = 0;
  const year = /^\d{4}$/.test(parts[0] || '') ? parts[idx++] : null;
  const make = parts[idx++] || null;
  let model = parts[idx++] || null;
  if (parts[idx] && MODEL_SUFFIX_RE.test(parts[idx])) {
    model = `${model} ${parts[idx]}`;
    idx += 1;
  }
  const trim = parts.slice(idx).join(' ').trim() || null;
  return { year, make, model, trim };
}
// ============================================================================
// Browser / page setup
// ============================================================================
async function launchBrowser() {
  return puppeteer.launch({
    headless: true,
    args: [
      '--disable-blink-features=AutomationControlled',
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
    ],
  });
}
async function configurePage(page, { isEntryPage = false } = {}) {
  await page.setUserAgent(USER_AGENT);
  await page.setViewport({ width: 1366, height: 900 });
  await page.setExtraHTTPHeaders({
    'accept-language': 'en-US,en;q=0.9',
    referer: `${BASE_URL}/`,
    'cache-control': 'max-age=0',
    'sec-ch-ua': SEC_CH_UA,
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"macOS"',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': isEntryPage ? 'none' : 'same-origin',
    'sec-fetch-user': '?1',
  });
  await page.evaluateOnNewDocument(() => {
    Object.defineProperty(navigator, 'webdriver', { get: () => false });
    window.chrome = window.chrome || { runtime: {} };
    Object.defineProperty(navigator, 'languages', { get: () => ['en-US', 'en'] });
    Object.defineProperty(navigator, 'plugins', { get: () => [1, 2, 3, 4, 5] });
  });
  await page.setRequestInterception(true);
  page.on('request', (req) => {
    if (BLOCKED_RESOURCE_TYPES.has(req.resourceType())) {
      req.abort();
    } else {
      req.continue();
    }
  });
}
async function gotoWithRetry(page, url, attempts = NAV_RETRY_ATTEMPTS) {
  let lastErr;
  for (let i = 0; i < attempts; i += 1) {
    try {
      const response = await page.goto(url, { waitUntil: 'domcontentloaded', timeout: NAV_TIMEOUT_MS });
      return response;
    } catch (err) {
      lastErr = err;
      console.warn(`    nav attempt ${i + 1}/${attempts} failed for ${url}: ${err.message}`);
      await delay(2000);
    }
  }
  throw lastErr;
}
function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
// ============================================================================
// Inventory sitemap
// ============================================================================
const LOC_TAG_RE = /<loc>([^<]+)<\/loc>/g;
function parseSitemapVdpUrls(xmlText) {
  const urls = [];
  let match;
  while ((match = LOC_TAG_RE.exec(xmlText)) !== null) {
    const loc = match[1].trim().replace(/&amp;/g, '&');
    if (isVdpUrl(loc)) {
      urls.push(loc);
    }
  }
  return urls;
}
async function fetchInventorySitemapUrls(warmedUpPage) {
  console.log(`Fetching inventory sitemap: ${SITEMAP_URL}`);
  const response = await gotoWithRetry(warmedUpPage, SITEMAP_URL);
  const status = response ? response.status() : null;
  const xmlText = await response.text();
  const urls = parseSitemapVdpUrls(xmlText);
  console.log(`  HTTP ${status}, ${xmlText.length} bytes, ${urls.length} VDP URLs found in sitemap`);
  if (urls.length === 0) {
    console.warn(`  Sitemap response preview: ${xmlText.slice(0, 300)}`);
  }
  return urls;
}
// ============================================================================
// VDP scrape
// ============================================================================
const LABEL_ALIASES = {
  exterior: 'Exterior',
  interior: 'Interior',
  drivetrain: 'Drivetrain',
  transmission: 'Transmission',
  engine: 'Engine',
  mileage: 'Mileage',
  'fuel type': 'Fuel Type',
  'body style': 'Body Style',
  stock: 'Stock',
  'stock #': 'Stock',
  vin: 'VIN',
};
async function scrapeVdp(browser, url) {
  const page = await browser.newPage();
  await configurePage(page);
  try {
    await gotoWithRetry(page, url);
    await page
      .waitForFunction(() => /mileage\s*:/i.test(document.body.innerText || ''), { timeout: 8000 })
      .catch(() => {});
    const vin = extractVinFromUrl(url);
    const condition = extractConditionFromUrl(url) || 'used';
    const data = await page.evaluate((vinArg, labelAliases) => {
      function resolveUrl(src) {
        try {
          return new URL(src, document.baseURI).href;
        } catch (e) {
          return src;
        }
      }
      const bodyText = document.body.innerText || '';
      const lines = bodyText
        .split('\n')
        .map((l) => l.trim())
        .filter(Boolean);
      const titleEl = document.querySelector('h1');
      const rawTitle = titleEl
        ? titleEl.textContent.trim().replace(/\s+/g, ' ')
        : (document.title || '').trim();
      const MAX_SPEC_VALUE_LENGTH = 120;
      function findLabeledValue(labelText) {
        const escaped = labelText.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const labelOnlyRe = new RegExp(`^${escaped}:?\\s*$`, 'i');
        for (let i = 0; i < lines.length; i += 1) {
          if (labelOnlyRe.test(lines[i])) {
            const value = (lines[i + 1] || '').trim();
            if (value && value.length <= MAX_SPEC_VALUE_LENGTH) return value;
          }
        }
        return null;
      }
      const specs = {};
      for (const aliasKey of Object.keys(labelAliases)) {
        const canonical = labelAliases[aliasKey];
        if (canonical in specs) continue;
        const value = findLabeledValue(aliasKey);
        if (value) specs[canonical] = value;
      }
      const specLineRe = /^([A-Za-z][A-Za-z .#]{1,30}):\s*(.+)$/;
      for (const line of lines) {
        const m = line.match(specLineRe);
        if (!m) continue;
        const canonical = labelAliases[m[1].trim().toLowerCase()];
        if (canonical && !(canonical in specs)) {
          specs[canonical] = m[2].trim();
        }
      }
      const specDebug = {};
      const debugTargets = ['Mileage', 'Exterior', 'Interior', 'Transmission', 'Engine'];
      for (const field of debugTargets) {
        if (!specs[field]) {
          const keyword = field.toLowerCase();
          specDebug[field] = lines.filter((l) => l.toLowerCase().includes(keyword));
        }
      }
      let msrp = null;
      let salesEvent = null;
      let netPrice = null;
      let fikesPrice = null;
      for (const line of lines) {
        let m;
        if ((m = line.match(/^MSRP\s*\$?\s*([\d,]+)/i))) {
          msrp = m[1].replace(/,/g, '');
        } else if ((m = line.match(/^Fikes Sales Event\s*-?\$?\s*([\d,]+)/i))) {
          salesEvent = m[1].replace(/,/g, '');
        } else if ((m = line.match(/^Net Price\s*\$?\s*([\d,]+)/i))) {
          netPrice = m[1].replace(/,/g, '');
        } else if ((m = line.match(/^Fikes Price\s*\$?\s*([\d,]+)/i))) {
          fikesPrice = m[1].replace(/,/g, '');
        }
      }
      const rawImgSrcs = Array.from(document.querySelectorAll('img'))
        .map((img) => {
          const raw =
            img.getAttribute('src') ||
            img.getAttribute('data-src') ||
            img.getAttribute('data-lazy-src') ||
            '';
          return raw ? resolveUrl(raw) : '';
        })
        .filter(Boolean);
      const srcsetUrls = Array.from(document.querySelectorAll('source, img'))
        .map((el) => el.getAttribute('srcset') || '')
        .filter(Boolean)
        .flatMap((ss) => ss.split(',').map((part) => resolveUrl(part.trim().split(' ')[0])));
      const allImgUrls = Array.from(new Set([...rawImgSrcs, ...srcsetUrls]));
      const vinUpper = (vinArg || '').toUpperCase();
      const images = allImgUrls.filter((src) => vinUpper && src.toUpperCase().includes(vinUpper));
      const daysInStockEl = document.querySelector('.days-hidden');
      const daysInStockRaw = daysInStockEl ? daysInStockEl.textContent.trim() : null;
      const daysInStock =
        daysInStockRaw && /^\d+$/.test(daysInStockRaw) ? parseInt(daysInStockRaw, 10) : null;
      return {
        rawTitle,
        specs,
        specDebug,
        pricing: { msrp, salesEvent, netPrice, fikesPrice },
        images,
        daysInStock,
      };
    }, vin, LABEL_ALIASES);
    if (data.specDebug && Object.keys(data.specDebug).length > 0) {
      console.log(`  Missing spec fields for VIN ${vin}: ${Object.keys(data.specDebug).join(', ')}`);
      try {
        fs.writeFileSync(`debug-specs-${vin || 'unknown'}.json`, JSON.stringify(data.specDebug, null, 2));
      } catch (err) {
        console.warn(`  Failed to write spec debug for ${vin}: ${err.message}`);
      }
    }
    if (data.images.length === 0) {
      console.log(`  WARNING: 0 VIN-matched images found for VIN ${vin} — will be excluded from feed.xml`);
    }
    let dateFirstOnLot = null;
    if (data.daysInStock != null) {
      const d = new Date();
      d.setUTCDate(d.getUTCDate() - data.daysInStock);
      dateFirstOnLot = d.toISOString().slice(0, 10);
    }
    const { year, make, model, trim } = parseTitle(data.rawTitle);
    const mileageRaw = data.specs.Mileage ? data.specs.Mileage.replace(/[^\d]/g, '') : null;
    const vehicle = {
      vin,
      condition,
      year,
      make,
      model,
      trim,
      title: data.rawTitle,
      url,
      exterior_color: data.specs.Exterior || null,
      interior_color: data.specs.Interior || null,
      drivetrain: data.specs.Drivetrain || null,
      transmission: data.specs.Transmission || null,
      engine: data.specs.Engine || null,
      mileage: mileageRaw ? parseInt(mileageRaw, 10) : null,
      fuel_type: data.specs['Fuel Type'] || null,
      body_style: data.specs['Body Style'] || null,
      stock_number: data.specs.Stock || null,
      days_in_stock: data.daysInStock,
      date_first_on_lot: dateFirstOnLot,
      pricing: {
        msrp: data.pricing.msrp ? parseInt(data.pricing.msrp, 10) : null,
        sales_event_discount: data.pricing.salesEvent ? parseInt(data.pricing.salesEvent, 10) : null,
        net_price: data.pricing.netPrice ? parseInt(data.pricing.netPrice, 10) : null,
        fikes_price: data.pricing.fikesPrice ? parseInt(data.pricing.fikesPrice, 10) : null,
      },
      price:
        condition === 'new'
          ? data.pricing.netPrice
            ? parseInt(data.pricing.netPrice, 10)
            : data.pricing.msrp
            ? parseInt(data.pricing.msrp, 10)
            : null
          : data.pricing.fikesPrice
          ? parseInt(data.pricing.fikesPrice, 10)
          : null,
      images: data.images,
    };
    return vehicle;
  } finally {
    await page.close();
  }
}
// ============================================================================
// Output: docs/inventory.json + docs/feed.xml
// ============================================================================
function escapeXml(value) {
  if (value === null || value === undefined) return '';
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
function buildDescription(v) {
  const bits = [];
  if (v.condition === 'used' && v.mileage != null) bits.push(`${v.mileage.toLocaleString()} miles`);
  if (v.exterior_color) bits.push(`${v.exterior_color} exterior`);
  if (v.interior_color) bits.push(`${v.interior_color} interior`);
  if (v.transmission) bits.push(v.transmission);
  if (v.engine) bits.push(v.engine);
  return bits.length ? bits.join(', ') : v.title;
}
const SUV_MODEL_HINTS = [
  'equinox', 'trailblazer', 'trax', 'traverse', 'suburban', 'tahoe', 'blazer',
  'xt4', 'xt5', '4runner', 'rav4', 'rogue', 'santa fe', 'cr-v', 'venza', 'glb', 'x3',
];
const PICKUP_MODEL_HINTS = ['silverado', 'sierra', 'f-150', 'tacoma', 'colorado'];
const VAN_MODEL_HINTS = ['sprinter', 'express', 'savana'];
function normalizeBodyStyle(v) {
  const raw = (v.body_style || '').toLowerCase();
  const model = (v.model || '').toLowerCase();
  const title = (v.title || '').toLowerCase();
  if (/sedan/.test(raw)) return 'SEDAN';
  if (/(sport utility|suv|activity vehicle)/.test(raw)) return 'SUV';
  if (/(cargo van|van)/.test(raw)) return 'VAN';
  if (/(pickup|cab)/.test(raw)) return 'PICKUP';
  if (VAN_MODEL_HINTS.some((m) => model.includes(m))) return 'VAN';
  if (PICKUP_MODEL_HINTS.some((m) => model.includes(m))) return 'PICKUP';
  if (SUV_MODEL_HINTS.some((m) => model.includes(m))) return 'SUV';
  if (/sedan/.test(title)) return 'SEDAN';
  if (/suv/.test(title)) return 'SUV';
  if (/(crew cab|pickup|truck)/.test(title)) return 'PICKUP';
  if (/van/.test(title)) return 'VAN';
  console.warn(
    `  No body_style match for VIN ${v.vin} (model="${v.model}", raw body_style="${v.body_style}") — defaulting to SUV`
  );
  return 'SUV';
}
function vehicleToFeedItem(v) {
  const price = v.price != null ? `${Number(v.price).toFixed(2)} USD` : '';
  const images = v.images || [];
  const bodyStyle = normalizeBodyStyle(v);
  const imageBlocks = images
    .map((img) => `    <image>\n      <url>${escapeXml(img)}</url>\n    </image>`)
    .join('\n');
  const dateFirstOnLotTag = v.date_first_on_lot
    ? `\n    <date_first_on_lot>${escapeXml(v.date_first_on_lot)}</date_first_on_lot>`
    : '';
  const customNumber0Tag = v.days_in_stock != null
    ? `\n    <custom_number_0>${v.days_in_stock}</custom_number_0>`
    : '';
  return `  <listing>
    <vehicle_id>${escapeXml(v.vin)}</vehicle_id>
    <description>${escapeXml(buildDescription(v))}</description>
    <url>${escapeXml(v.url)}</url>
    <title>${escapeXml(v.title)}</title>
    <body_style>${bodyStyle}</body_style>
    <price>${price}</price>
    <address format="simple">
      <component name="addr1">${escapeXml(DEALER_ADDRESS.street)}</component>
      <component name="city">${escapeXml(DEALER_ADDRESS.city)}</component>
      <component name="region">${escapeXml(DEALER_ADDRESS.state)}</component>
      <component name="postal_code">${escapeXml(DEALER_ADDRESS.zip)}</component>
      <component name="country">${escapeXml(DEALER_ADDRESS.country)}</component>
    </address>
    <make>${escapeXml(v.make)}</make>
    <model>${escapeXml(v.model)}</model>
    <year>${escapeXml(v.year)}</year>
    <vin>${escapeXml(v.vin)}</vin>
    <state_of_vehicle>${v.condition === 'new' ? 'NEW' : 'USED'}</state_of_vehicle>
    <mileage>
      <unit>MI</unit>
      <value>${v.mileage != null ? v.mileage : 0}</value>
    </mileage>
    <transmission>${escapeXml(v.transmission)}</transmission>
    <drivetrain>${escapeXml(v.drivetrain)}</drivetrain>
    <exterior_color>${escapeXml(v.exterior_color)}</exterior_color>
    <interior_color>${escapeXml(v.interior_color)}</interior_color>
    <vehicle_type>car_truck</vehicle_type>${dateFirstOnLotTag}${customNumber0Tag}
${imageBlocks}
  </listing>`;
}
function writeOutputs(vehicles) {
  if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  const noImageVehicles = vehicles.filter((v) => !v.images || v.images.length === 0);
  if (noImageVehicles.length > 0) {
    console.log(
      `${noImageVehicles.length} vehicle(s) have 0 images and will be EXCLUDED from feed.xml ` +
        '(still present in inventory.json for visibility): ' +
        noImageVehicles.map((v) => v.vin).join(', ')
    );
  }
  const noDaysInStockVehicles = vehicles.filter((v) => v.days_in_stock == null);
  if (noDaysInStockVehicles.length > 0) {
    console.log(
      `${noDaysInStockVehicles.length} vehicle(s) missing days_in_stock (the hidden ` +
        '.days-hidden DI block wasn\'t found on their VDP — check for a stale ' +
        'Cloudflare cache on that specific page before assuming a real problem): ' +
        noDaysInStockVehicles.map((v) => v.vin).join(', ')
    );
  }
  const jsonOut = {
    generated_at: new Date().toISOString(),
    pixel_id: PIXEL_ID,
    dealer_address: DEALER_ADDRESS,
    total_vehicles: vehicles.length,
    new_count: vehicles.filter((v) => v.condition === 'new').length,
    used_count: vehicles.filter((v) => v.condition === 'used').length,
    no_image_count: noImageVehicles.length,
    no_image_vins: noImageVehicles.map((v) => v.vin),
    no_days_in_stock_count: noDaysInStockVehicles.length,
    no_days_in_stock_vins: noDaysInStockVehicles.map((v) => v.vin),
    vehicles,
  };
  fs.writeFileSync(path.join(OUTPUT_DIR, 'inventory.json'), JSON.stringify(jsonOut, null, 2));
  const feedVehicles = vehicles.filter((v) => v.images && v.images.length > 0);
  const items = feedVehicles.map(vehicleToFeedItem).join('\n');
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Fikes Vehicles — Meta Commerce Manager automotive inventory feed -->
<!-- Pixel ID ${PIXEL_ID} is associated with this catalog via Commerce -->
<!-- Manager > Settings > Event Sources, not via this feed file. -->
<!-- ${noImageVehicles.length} vehicle(s) excluded from this feed for having -->
<!-- 0 real images (see inventory.json no_image_vins for the list). -->
<listings>
  <title>Fikes Vehicles</title>
${items}
</listings>
`;
  fs.writeFileSync(path.join(OUTPUT_DIR, 'feed.xml'), xml);
  console.log(
    `Wrote ${vehicles.length} vehicles -> ${path.join(OUTPUT_DIR, 'inventory.json')} ` +
      `and ${feedVehicles.length} vehicles -> ${path.join(OUTPUT_DIR, 'feed.xml')} ` +
      `(${noImageVehicles.length} excluded from feed for 0 images)`
  );
}
function validateFeedXml(feedPath) {
  const xml = fs.readFileSync(feedPath, 'utf8');
  const result = XMLValidator.validate(xml, { allowBooleanAttributes: true });
  if (result !== true) {
    const { code, msg, line, col } = result.err;
    throw new Error(`feed.xml failed XML validation: [${code}] ${msg} (line ${line}, col ${col})`);
  }
  const commentRe = /<!--([\s\S]*?)-->/g;
  const offenders = [];
  let match;
  while ((match = commentRe.exec(xml)) !== null) {
    if (match[1].includes('--')) {
      offenders.push(match[1].trim());
    }
  }
  if (offenders.length > 0) {
    throw new Error(
      `feed.xml has ${offenders.length} XML comment(s) containing an illegal "--" sequence: ${offenders.join(' | ')}`
    );
  }
  const stripped = xml
    .replace(/<\?xml[\s\S]*?\?>/, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .trim();
  if (!/^<listings[\s>]/.test(stripped)) {
    throw new Error(
      'feed.xml root element is not <listings> — this is required for Meta\'s Vehicles catalog schema. ' +
        'If you see <rss> here, the feed has regressed to the generic product-feed format, which Commerce ' +
        'Manager rejects entirely for this catalog type.'
    );
  }
  console.log(`feed.xml passed XML validation (${feedPath})`);
}
// ============================================================================
// Main
// ============================================================================
async function main() {
  const browser = await launchBrowser();
  const allVehicles = [];
  try {
    const warmupPage = await browser.newPage();
    await configurePage(warmupPage, { isEntryPage: true });
    console.log(`Warming up session: ${BASE_URL}`);
    await gotoWithRetry(warmupPage, BASE_URL);
    await delay(REQUEST_DELAY_MS);
    const vdpUrls = await fetchInventorySitemapUrls(warmupPage);
    await warmupPage.close();
    for (const url of vdpUrls) {
      console.log(`  scraping: ${url}`);
      try {
        const vehicle = await scrapeVdp(browser, url);
        allVehicles.push(vehicle);
      } catch (err) {
        console.warn(`  FAILED to scrape ${url}: ${err.message}`);
      }
      await delay(REQUEST_DELAY_MS);
    }
  } finally {
    await browser.close();
  }
  console.log(`Scraped ${allVehicles.length} total VDP records (pre-dedupe).`);
  const seen = new Set();
  const finalVehicles = allVehicles.filter((v) => {
    if (seen.has(v.vin)) return false;
    seen.add(v.vin);
    return true;
  });
  console.log(`Final vehicle count after one-time VIN dedupe: ${finalVehicles.length}`);
  const MIN_EXPECTED_VEHICLES = 10;
  if (finalVehicles.length < MIN_EXPECTED_VEHICLES) {
    throw new Error(
      `Only ${finalVehicles.length} vehicle(s) scraped — below the safety threshold of ` +
        `${MIN_EXPECTED_VEHICLES}. Refusing to write or commit feed.xml/inventory.json to avoid ` +
        'overwriting the live catalog with bad data. This usually means the sitemap fetch was ' +
        'blocked or returned unexpectedly little content — check the "Fetching inventory sitemap" ' +
        'log lines above for the actual HTTP status and response preview before assuming the ' +
        'dealership inventory is genuinely this small.'
    );
  }
  writeOutputs(finalVehicles);
  validateFeedXml(path.join(OUTPUT_DIR, 'feed.xml'));
}
if (require.main === module) {
  main().catch((err) => {
    console.error('Fatal error:', err);
    process.exitCode = 1;
  });
}
module.exports = {
  extractVinFromUrl,
  extractConditionFromUrl,
  parseTitle,
  isVdpUrl,
  parseSitemapVdpUrls,
  normalizeBodyStyle,
  vehicleToFeedItem,
  writeOutputs,
  validateFeedXml,
};
